### ISSUE TITLE
Update download link and instructions for Firefox Nightly to 64-bit

### ISSUE THREAD

**Issue by kearwood** [immersive-web/webvrrocks#257]
On https://webvr.rocks/firefox, the link to Firefox Nightly downloads the 32-bit version, which no longer has WebVR enabled by default.

WebVR will also be enabled in release builds of Firefox starting in 55, so perhaps the directions on this page should be updated to provide links to both the 64-bit Release version and 64-bit Nightly.

**Comment by cvan** [comment]
fixed a while back in PR #258
