### ISSUE TITLE
adjust Oculus Browser FAQ re: deprecated `ovrweb:` protocol handler

### ISSUE THREAD

**Issue by cvan** [immersive-web/webvrrocks#276]
https://webvr.rocks/oculus_browser#faq_navigating

**Comment by vincentfretin** [comment]
ovrweb: links doesn't work anymore indeed.

You can install https://play.google.com/store/apps/details?id=com.machenmusik.launchoculusbrowser if you want to open oculus browser when you click ovrweb: links from chrome when in developer mode.

**Comment by cvan** [comment]
done in PR #278
