### ISSUE TITLE
WebVR on Ubuntu

### ISSUE THREAD

**Issue by fnielsen** [immersive-web/webvrrocks#280]
It is unclear to me if the combination Ubuntu, Firefox and HTC Vive (or Oculus) works when reading the overview tables on the main page https://webvr.rocks/

**Comment by cvan** [comment]
I will test this and follow up in this issue with the status and, if possible, instructions.

I’ll create a page for you https://webvr.rocks/linux with a specific section for https://webvr.rocks/linux/ubuntu.

Thanks for filing. Appreciate it a lot. :+1:

**Comment by arcriley** [comment]
I was curious about this too, also would be nice to see it on the frontpage support matrix.

**Comment by promethe42** [comment]
@cvan any update on this?

**Comment by Scary-Guy** [comment]
> I will test this and follow up in this issue with the status and, if possible, instructions.
> 
> I’ll create a page for you https://webvr.rocks/linux with a specific section for https://webvr.rocks/linux/ubuntu.
> 
> Thanks for filing. Appreciate it a lot. +1

Where is the page?  All I get is a redirect to the Linux entry on Wikipedia for both of those links.

**Comment by AdaRoseCannon** [comment]
WebVR Rocks isn't maintained anymore. This is issue is 5 years old.

https://immersiveweb.dev is the current main source.

**Comment by himorin** [comment]
@AdaRoseCannon it seems travis to update gh-pages is not working. Let me check and/or change something... (switch to ghaction or force push locally compiled assets,,, etc.)

**Comment by himorin** [comment]
closing, redirect is now active.
