### ISSUE TITLE
Deprecate / update to point to WebXR?

### ISSUE THREAD

**Issue by dontcallmedom** [immersive-web/webvrrocks#313]
While WebVR rocked, WebXR now rules - the web site should probably reflect that.

**Comment by cvan** [comment]
sure thing. I own webvr.rocks. shall I have it redirected to https://immersiveweb.dev/?

**Comment by AdaRoseCannon** [comment]
That's a great idea!

**Comment by kylebakerio** [comment]
@cvan hey could you get to this? this info is super out of date

**Comment by cvan** [comment]
sure thing. thanks for flagging! @dontcallmedom, et al: could you review & merge [PR #328](https://github.com/immersive-web/webvrrocks/pull/328) that redirects https://webvr.rocks to https://immersiveweb.dev/?
